/**
 * Proxy for the delivery export.
 *
 * A route handler rather than a server action, because the response is a file. Server actions
 * return serialisable values, so a workbook would have to be base64'd through the RSC payload and
 * reassembled in the browser — which doubles the bytes and loses `Content-Disposition`, the thing
 * that gives the download its filename.
 *
 * It exists for the same reason `actions.ts` does: the browser never talks to the FastAPI service
 * directly. That keeps `AXIOM_API_URL` server-side, means there is no CORS configuration anywhere,
 * and leaves exactly one place to add auth in front of an endpoint that is currently unauthenticated
 * and does real work.
 *
 * The body is streamed through rather than parsed. Reading it as `FormData` here would buffer the
 * whole upload in this process before the API had a chance to reject it for size, which would make
 * the Python-side cap useless as a memory bound.
 */

import type { NextRequest } from "next/server";

import { API_BASE } from "@/lib/data";

/**
 * Total request budget, generous enough for one item master plus its documents at the API's own
 * per-file caps, and checked here so an oversized upload is refused before it is forwarded.
 *
 * The API enforces its own limits per file regardless; this is the cheap early exit, not the
 * authority. `Content-Length` is a claim by the caller, which is precisely why the real check
 * stays where the bytes are counted.
 */
const MAX_REQUEST_BYTES = 300 * 1024 * 1024;

/**
 * Long enough for a real batch. A thousand rows against the deterministic path takes roughly
 * twenty seconds, and the default fetch timeout would abandon it mid-run and report a network
 * error for work that was going to succeed.
 */
const TIMEOUT_MS = 300_000;

/** Headers worth passing back: the filename, and the run summary the API reports numerically. */
const FORWARDED = [
  "content-type",
  "content-disposition",
  "x-axiom-rows",
  "x-axiom-rows-skipped",
  "x-axiom-columns-populated",
  "x-axiom-columns-total",
  "x-axiom-withheld",
  "x-axiom-compliant",
  "x-axiom-content-hash",
];

export async function POST(request: NextRequest): Promise<Response> {
  const contentType = request.headers.get("content-type");
  if (!contentType?.includes("multipart/form-data")) {
    return problem(415, "Expected a multipart/form-data upload.");
  }

  const declared = Number(request.headers.get("content-length") ?? 0);
  if (declared > MAX_REQUEST_BYTES) {
    return problem(
      413,
      `That upload is ${(declared / (1024 * 1024)).toFixed(0)} MiB, over the ` +
        `${MAX_REQUEST_BYTES / (1024 * 1024)} MiB request limit. For a file that size use ` +
        `scripts/export_delivery.py, which streams to disk and has no request timeout.`,
    );
  }

  if (request.body === null) {
    return problem(400, "The upload had no body.");
  }

  let upstream: Response;
  try {
    upstream = await fetch(`${API_BASE}/api/delivery/export`, {
      method: "POST",
      // Forwarded verbatim so the multipart boundary in the header still matches the body.
      headers: { "content-type": contentType },
      body: request.body,
      // Required by undici whenever the body is a stream: it declares that this side will finish
      // sending before it starts reading, which is what an ordinary request does.
      duplex: "half",
      signal: AbortSignal.timeout(TIMEOUT_MS),
    } as RequestInit & { duplex: "half" });
  } catch (cause) {
    const reason = cause instanceof Error ? cause.message : String(cause);
    return problem(
      502,
      `Could not reach the AXIOM API at ${API_BASE} (${reason}). Start it with ` +
        `"python -m uvicorn apps.api.main:app --port 8000".`,
    );
  }

  const headers = new Headers();
  for (const name of FORWARDED) {
    const value = upstream.headers.get(name);
    if (value !== null) headers.set(name, value);
  }
  // These are generated bytes derived from a caller's upload; nothing should sniff or cache them.
  headers.set("x-content-type-options", "nosniff");
  headers.set("cache-control", "no-store");

  // Streamed back rather than buffered, so a thousand-row workbook does not sit in this process
  // in full before the browser sees any of it.
  return new Response(upstream.body, { status: upstream.status, headers });
}

function problem(status: number, message: string): Response {
  // Shaped like FastAPI's error body so the client has one error path to read, whether the failure
  // happened here or upstream.
  return Response.json({ detail: message }, { status });
}
