"""Bedrock token prices, fetched from AWS rather than authored.

``prices.yaml`` is generated by ``scripts/fetch_bedrock_prices.py`` from the AWS Price List
Query API. Nothing here invents a number: if a model has no published on-demand price, it is
absent from the table and any run that used it reports no cost at all.

That refusal is the point. A cost-per-SKU figure is the number a buyer uses to decide whether
the system is affordable at 500,000 SKUs, and a plausible-but-wrong one is worse than a blank,
because a blank prompts a question while a wrong number ends the conversation.

The table is keyed by model ID, while ``UsageLedger`` counts tokens by cascade *tier*. The
translation needs the cascade, so it lives in :meth:`PriceTable.tier_prices` rather than being
assumed anywhere.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

import yaml

DEFAULT_PATH = Path(__file__).resolve().parents[1] / "config" / "prices.yaml"

STALE_AFTER_DAYS = 90
"""Beyond this, the table is reported as stale. AWS changes prices; a year-old table quietly
misrepresents unit economics, and the fix is one command."""


@dataclass(frozen=True)
class ModelPrice:
    """On-demand token price for one model, in USD per million tokens."""

    input_per_million_usd: float
    output_per_million_usd: float
    effective_date: str | None = None
    publication_date: str | None = None
    note: str | None = None

    @property
    def as_tuple(self) -> tuple[float, float]:
        return (self.input_per_million_usd, self.output_per_million_usd)


@dataclass(frozen=True)
class PriceTable:
    """Model prices for one region, with the provenance needed to audit them."""

    region: str
    fetched_at: str
    source: str
    models: dict[str, ModelPrice]
    unpriced: tuple[str, ...] = ()

    @classmethod
    def load(cls, path: Path | str | None = None) -> PriceTable | None:
        """Read the generated table. Returns None when it has never been fetched.

        None rather than an empty table, and rather than raising: cost reporting is optional,
        and a pipeline should run fine on an account whose prices were never pulled.
        """
        target = Path(path) if path else DEFAULT_PATH
        if not target.is_file():
            return None

        payload = yaml.safe_load(target.read_text(encoding="utf-8")) or {}
        models = {
            model_id: ModelPrice(
                input_per_million_usd=float(entry["input_per_million_usd"]),
                output_per_million_usd=float(entry["output_per_million_usd"]),
                effective_date=entry.get("effective_date"),
                publication_date=entry.get("publication_date"),
                note=entry.get("note"),
            )
            for model_id, entry in (payload.get("models") or {}).items()
        }
        return cls(
            region=payload.get("region", ""),
            fetched_at=payload.get("fetched_at", ""),
            source=payload.get("source", ""),
            models=models,
            unpriced=tuple(payload.get("unpriced") or ()),
        )

    def tier_prices(self, cascade) -> dict[str, tuple[float, float]]:
        """``{tier: (usd_per_million_in, usd_per_million_out)}`` for every priced tier.

        Tiers whose model has no price are simply omitted. ``UsageLedger.cost_usd`` then
        returns None only if one of those tiers was actually *used*, which keeps an unpriced
        vision model from blanking the cost of a run that never called it.
        """
        prices: dict[str, tuple[float, float]] = {}
        for tier, model_id in cascade.tiers.items():
            price = self.models.get(model_id)
            if price is not None:
                prices[tier] = price.as_tuple
        return prices

    def age_days(self) -> float | None:
        if not self.fetched_at:
            return None
        try:
            fetched = datetime.fromisoformat(self.fetched_at)
        except ValueError:
            return None
        if fetched.tzinfo is None:
            fetched = fetched.replace(tzinfo=UTC)
        return (datetime.now(UTC) - fetched).total_seconds() / 86400

    @property
    def is_stale(self) -> bool:
        age = self.age_days()
        return age is not None and age > STALE_AFTER_DAYS

    def summary(self) -> dict[str, object]:
        return {
            "region": self.region,
            "fetched_at": self.fetched_at,
            "source": self.source,
            "priced_models": len(self.models),
            "unpriced_models": list(self.unpriced),
            "age_days": round(self.age_days(), 1) if self.age_days() is not None else None,
            "stale": self.is_stale,
        }


def load_prices(path: Path | str | None = None) -> PriceTable | None:
    """Convenience wrapper matching the other loaders in this package."""
    return PriceTable.load(path)
