"""Source Fabric: turn every arrival channel into one hashed, attributed artifact."""

from axiom.ingest.columns import (
    RECORD_FIELDS,
    SYNONYMS,
    ColumnMapping,
    ColumnMatch,
    MappingMemory,
    fold_header,
    infer_mapping,
)
from axiom.ingest.fabric import (
    FLAT_FILE_SUFFIXES,
    FlatFile,
    IngestedArtifact,
    IngestError,
    detect_document_type,
    ingest_bytes,
    ingest_file,
    pdf_page_count,
    read_flat_file,
)
from axiom.ingest.store import (
    ArtifactStore,
    LocalArtifactStore,
    artifact_key,
    sha256_bytes,
    sha256_file,
)
from axiom.ingest.web import (
    ALLOWED_SCHEMES,
    DEFAULT_MAX_BYTES,
    DEFAULT_TIMEOUT,
    USER_AGENT,
    FetchedResource,
    Fetcher,
    UrlFetchError,
    fetch_url,
    filename_for,
    ingest_url,
    is_url,
)

__all__ = [
    "ALLOWED_SCHEMES",
    "DEFAULT_MAX_BYTES",
    "DEFAULT_TIMEOUT",
    "FLAT_FILE_SUFFIXES",
    "RECORD_FIELDS",
    "SYNONYMS",
    "USER_AGENT",
    "ArtifactStore",
    "ColumnMapping",
    "ColumnMatch",
    "FetchedResource",
    "Fetcher",
    "FlatFile",
    "IngestError",
    "IngestedArtifact",
    "LocalArtifactStore",
    "MappingMemory",
    "UrlFetchError",
    "artifact_key",
    "detect_document_type",
    "fetch_url",
    "filename_for",
    "fold_header",
    "infer_mapping",
    "ingest_bytes",
    "ingest_file",
    "ingest_url",
    "is_url",
    "pdf_page_count",
    "read_flat_file",
    "sha256_bytes",
    "sha256_file",
]
