"""Fetch real Bedrock token prices from the AWS Pricing API and pin them.

``UsageLedger.cost_usd`` returns None unless it is handed a price table, and that is
deliberate: a made-up per-token price produces a confident number that is wrong, and a
plausible cost-per-SKU figure invites decisions about whether the system is economically
viable. So the price table is *fetched*, never authored.

This is the same pattern as ``preflight_bedrock.py``: talk to AWS, write a generated config,
record enough provenance that the number can be audited later. The output carries the price's
own ``effectiveDate`` and AWS's ``publicationDate``, so a stale table is visible rather than
silently wrong.

Models are matched on **usagetype**, not on the display name. A record's usagetype embeds the
model ID verbatim (``USE2-zai.glm-4.7-flash-output-tokens``), whereas the ``model`` attribute is
a human label (``GLM 4.7 Flash``) whose relationship to ``zai.glm-4.7-flash`` is a guess.
Matching on the label would break the first time AWS renamed one.

Run it::

    $env:AWS_PROFILE = "axiom"
    python scripts/fetch_bedrock_prices.py --write

The Pricing API only exists in a few regions, so the *client* region is fixed while the region
being priced comes from models.yaml.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import defaultdict
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT / "packages") not in sys.path:
    sys.path.insert(0, str(REPO_ROOT / "packages"))

import yaml  # noqa: E402
from axiom.extract import ModelCascade  # noqa: E402

CONFIG_DIR = REPO_ROOT / "packages" / "axiom" / "config"
DEFAULT_OUT = CONFIG_DIR / "prices.yaml"

PRICING_API_REGION = "us-east-1"
"""The Pricing API is not available in every region; us-east-1 always has it."""

TOKENS_PER_UNIT = 1_000
"""Bedrock prices are quoted per 1K tokens. We store per-million to match how they are
normally discussed, and because per-1K figures are small enough that reading them invites
order-of-magnitude mistakes."""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--profile", default=None)
    parser.add_argument(
        "--region",
        default=None,
        help="region to price; defaults to the region pinned in models.yaml",
    )
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--write", action="store_true", help="persist prices.yaml")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()

    cascade = ModelCascade.load()
    region = args.region or cascade.region

    # Every distinct model ID the cascade can reach, including the embedding model, because a
    # RAG stage will bill for embeddings and leaving them out would understate the true cost.
    wanted: dict[str, list[str]] = defaultdict(list)
    for tier, model_id in cascade.tiers.items():
        wanted[model_id].append(tier)
    if cascade.embedding_model:
        wanted[cascade.embedding_model].append("embedding")

    print(f"pricing {len(wanted)} model(s) in {region}")
    for model_id, tiers in sorted(wanted.items()):
        print(f"  {model_id:<34} {', '.join(sorted(tiers))}")

    try:
        records = _fetch(region, profile=args.profile)
    except Exception as exc:  # noqa: BLE001 - surface any boto/credential failure plainly
        print(f"\nfailed to reach the Pricing API: {exc}", file=sys.stderr)
        return 1
    print(f"\nfetched {len(records)} Bedrock price records for {region}")

    resolved, unresolved = _resolve(records, set(wanted))
    _report(resolved, unresolved, wanted)

    if unresolved:
        print(
            "\nSome models have no on-demand token price in this region. Cost reporting stays "
            "disabled for any tier using them, which is the intended behaviour: a partial "
            "price table would silently undercount.",
            file=sys.stderr,
        )

    payload = {
        "region": region,
        "fetched_at": datetime.now(UTC).isoformat(),
        "source": "AWS Price List Query API (AmazonBedrock)",
        "unit": "USD per million tokens",
        "note": (
            "GENERATED by scripts/fetch_bedrock_prices.py. Do not hand-edit; re-run the "
            "script. On-demand standard rates only — batch, flex and priority tiers are "
            "priced differently and this pipeline does not use them."
        ),
        "models": resolved,
        "unpriced": unresolved,
    }

    if args.json:
        print(json.dumps(payload, indent=2))

    if args.write:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(
            yaml.safe_dump(payload, sort_keys=False, allow_unicode=True), encoding="utf-8"
        )
        print(f"\nwrote {args.out.relative_to(REPO_ROOT)}")
    else:
        print("\n(dry run — pass --write to persist)")

    return 0 if resolved else 1


def _fetch(region: str, *, profile: str | None) -> list[dict[str, Any]]:
    """Every AmazonBedrock price record for one region."""
    import boto3

    session = boto3.Session(profile_name=profile, region_name=PRICING_API_REGION)
    client = session.client("pricing")

    records: list[dict[str, Any]] = []
    paginator = client.get_paginator("get_products")
    pages = paginator.paginate(
        ServiceCode="AmazonBedrock",
        Filters=[{"Type": "TERM_MATCH", "Field": "regionCode", "Value": region}],
    )
    for page in pages:
        for raw in page["PriceList"]:
            records.append(json.loads(raw))
    return records


# `USE2-zai.glm-4.7-flash-mantle-input-tokens-standard` decomposes into a region prefix, the
# model stem, an optional "mantle-" infix, the metered dimension, and an optional service tier.
# Stripping "mantle-" makes the plain and mantle usagetypes collapse onto the same stem, which
# is what we want: they are the same model at the same rate under two naming conventions.
_USAGETYPE = re.compile(
    r"^(?:[A-Z0-9]+-)?(?P<stem>.+?)-(?:mantle-)?"
    r"(?P<dimension>input|output)-tokens"
    r"(?:-(?P<service_tier>standard|flex|batch|priority))?$"
)

# Models whose price-list name cannot be derived from the model ID at all. Bedrock meters Titan
# embeddings as "TitanEmbeddingV2-Text", which shares no substring with
# "amazon.titan-embed-text-v2:0". Anything requiring a hand-written mapping goes here so it is
# visible and reviewable rather than buried in matching heuristics.
STEM_ALIASES = {
    "TitanEmbeddingV2-Text": "amazon.titan-embed-text-v2:0",
}


def _normalise(name: str) -> str:
    """Strip punctuation and case for comparison.

    The price list is not consistent with the model IDs about punctuation: ``zai.glm-5`` is
    metered as ``zai.glm5``, while ``zai.glm-4.7-flash`` keeps every hyphen. Comparing raw
    strings therefore silently loses whichever models AWS happened to spell differently, and
    the failure looks exactly like "this model has no price" — which is indistinguishable from
    the legitimate case.
    """
    return re.sub(r"[^a-z0-9]", "", name.casefold())

# Embedding models are billed on input only: they emit vectors, not tokens. Requiring an output
# rate for these would report them as unpriced and disable cost reporting for the whole run.
INPUT_ONLY_PREFIXES = ("amazon.titan-embed",)


def _resolve(
    records: list[dict[str, Any]], wanted: set[str]
) -> tuple[dict[str, dict[str, Any]], list[str]]:
    """Assign price records to pinned model IDs.

    Each usagetype stem is matched to the **longest** pinned model ID that it equals or extends.
    That resolves two real cases at once: ``qwen.qwen3-vl-235b-a22b-instruct`` extends the
    pinned ``qwen.qwen3-vl-235b-a22b``, and ``zai.glm-4.7-flash`` must bind to the flash tier
    rather than to ``zai.glm-4.7`` even though the latter is also a prefix of it. Taking the
    first or shortest match would price the flash tier as the mid tier — a silent 8x error.
    """
    by_stem: dict[str, dict[str, dict[str, Any]]] = defaultdict(dict)

    for record in records:
        attributes = record.get("product", {}).get("attributes", {})
        match = _USAGETYPE.match(attributes.get("usagetype", ""))
        if not match:
            continue

        # Standard on-demand only. An absent `service_tier` is the plain on-demand SKU;
        # explicit "standard" is the same rate under the newer naming.
        if match.group("service_tier") not in (None, "standard"):
            continue

        price = _unit_price(record)
        if price is None:
            continue

        stem, dimension = match.group("stem"), match.group("dimension")
        existing = by_stem[stem].get(dimension)
        # Keep the cheaper if the plain and mantle rates ever disagree, so an estimate never
        # overstates by accident.
        if existing is None or price["per_million"] < existing["per_million"]:
            by_stem[stem][dimension] = price

    merged: dict[str, dict[str, dict[str, Any]]] = defaultdict(dict)
    for stem, dimensions in by_stem.items():
        model_id = STEM_ALIASES.get(stem) or _longest_match(stem, wanted)
        if model_id is None:
            continue
        for dimension, price in dimensions.items():
            existing = merged[model_id].get(dimension)
            if existing is None or price["per_million"] < existing["per_million"]:
                merged[model_id][dimension] = price

    resolved: dict[str, dict[str, Any]] = {}
    unresolved: list[str] = []
    for model_id in sorted(wanted):
        dimensions = merged.get(model_id, {})
        input_only = model_id.startswith(INPUT_ONLY_PREFIXES)

        if "input" not in dimensions or (not input_only and "output" not in dimensions):
            unresolved.append(model_id)
            continue

        entry = {
            "input_per_million_usd": dimensions["input"]["per_million"],
            "output_per_million_usd": (
                dimensions["output"]["per_million"] if "output" in dimensions else 0.0
            ),
            "effective_date": dimensions["input"]["effective_date"],
            "publication_date": dimensions["input"]["publication_date"],
        }
        if input_only:
            entry["note"] = "billed on input tokens only; embeddings emit vectors, not tokens"
        resolved[model_id] = entry

    return resolved, unresolved


def _longest_match(stem: str, wanted: set[str]) -> str | None:
    """Bind a usagetype stem to the longest pinned model ID it equals or extends.

    Longest wins because several pinned IDs can be prefixes of one stem:
    ``zai.glm-4.7-flash`` must not bind to ``zai.glm-4.7``, which would price the cheapest tier
    at roughly 8x its real rate and make the cost meter useless in the flattering direction.

    Exact comparison is tried before the punctuation-insensitive fallback, so a model that does
    spell itself consistently can never be captured by a sloppier near-match.
    """
    exact = [
        model_id
        for model_id in wanted
        if stem == model_id or stem.startswith(f"{model_id}-")
    ]
    if exact:
        return max(exact, key=len)

    normalised_stem = _normalise(stem)
    loose = [
        model_id
        for model_id in wanted
        if normalised_stem.startswith(_normalise(model_id))
    ]
    return max(loose, key=lambda model_id: len(_normalise(model_id))) if loose else None


def _unit_price(record: dict[str, Any]) -> dict[str, Any] | None:
    """Pull the USD rate out of a price record and normalise it to per-million tokens."""
    on_demand = record.get("terms", {}).get("OnDemand", {})
    for term in on_demand.values():
        for dimension in term.get("priceDimensions", {}).values():
            usd = dimension.get("pricePerUnit", {}).get("USD")
            if usd is None:
                continue
            unit = dimension.get("unit", "")
            if "1K" not in unit and "1000" not in unit:
                # An unexpected unit would silently scale the whole estimate.
                continue
            per_million = round(float(usd) * (1_000_000 / TOKENS_PER_UNIT), 6)
            return {
                "per_million": per_million,
                "effective_date": term.get("effectiveDate"),
                "publication_date": record.get("publicationDate"),
            }
    return None


def _report(
    resolved: dict[str, dict[str, Any]],
    unresolved: list[str],
    wanted: dict[str, list[str]],
) -> None:
    print("\n" + "=" * 78)
    print("ON-DEMAND TOKEN PRICES (USD per million)")
    print("=" * 78)
    print(f"  {'model':<34} {'input':>10} {'output':>10}   tiers")
    print("  " + "-" * 74)
    for model_id, price in sorted(resolved.items()):
        print(
            f"  {model_id:<34} {price['input_per_million_usd']:>10.4f} "
            f"{price['output_per_million_usd']:>10.4f}   {', '.join(sorted(wanted[model_id]))}"
        )
    for model_id in unresolved:
        print(f"  {model_id:<34} {'—':>10} {'—':>10}   NO PRICE FOUND")

    dates = {p["effective_date"] for p in resolved.values() if p.get("effective_date")}
    if dates:
        print(f"\n  price list effective: {', '.join(sorted(dates))}")


if __name__ == "__main__":
    raise SystemExit(main())
